@startuml

entity Kandidat {
    * kandidatnr : INTEGER
    * fornavn : VARCHAR
    * etternavn : VARCHAR
    * telefon : VARCHAR
    * epost : VARCHAR
}

entity Bedrift {
    * organisasjonsnr : VARCHAR
    * navn : VARCHAR
    * telefon : VARCHAR
    * epost : VARCHAR
}

entity Kvalifikasjon {
    * kvalifikasjonsnr : INTEGER
    * navn : VARCHAR
}

entity Oppdrag {
    * oppdragsnr : INTEGER
    * bedriftsnavn : VARCHAR
    * kvalifikasjon : VARCHAR
    * startdato : DATE
    * sluttdato : DATE
}

entity Jobbhistorikk {
    * historikk_id : INTEGER
    * kandidatnr : INTEGER
    * oppdragsnr : INTEGER
    * startdato : DATE
    * sluttdato : DATE
    * timer_arbeidet : INTEGER
}

entity Sluttattest {
    * attest_id : INTEGER
    * oppdragsnr : INTEGER
    * kandidatnr : INTEGER
    * beskrivelse : TEXT
}

@enduml
